/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#25005a",
        "inverse-surface": "#263143",
        "on-error": "#ffffff",
        "secondary-fixed": "#eaddff",
        "on-primary-container": "#eeefff",
        "inverse-on-surface": "#ecf1ff",
        "on-tertiary": "#ffffff",
        background: "#f9f9ff",
        "on-tertiary-fixed": "#191c1e",
        outline: "#737686",
        "on-surface-variant": "#434655",
        secondary: "#712ae2",
        surface: "#f9f9ff",
        "secondary-fixed-dim": "#d2bbff",
        "on-background": "#111c2d",
        "on-primary-fixed": "#00174b",
        "on-primary": "#ffffff",
        "inverse-primary": "#b4c5ff",
        "on-surface": "#111c2d",
        "on-tertiary-container": "#eff1f3",
        "tertiary-fixed": "#e0e3e5",
        "on-tertiary-fixed-variant": "#444749",
        primary: "#004ac6",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#c4c7c9",
        error: "#ba1a1a",
        tertiary: "#525657",
        "on-secondary-fixed-variant": "#5a00c6",
        "outline-variant": "#c3c6d7",
        "surface-bright": "#f9f9ff",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#003ea8",
        "on-secondary": "#ffffff",
        "primary-fixed": "#dbe1ff",
        "surface-container": "#e7eeff",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#d8e3fb",
        "secondary-container": "#8a4cfc",
        "surface-dim": "#cfdaf2",
        "primary-fixed-dim": "#b4c5ff",
        "surface-container-low": "#f0f3ff",
        "primary-container": "#2563eb",
        "surface-container-high": "#dee8ff",
        "on-secondary-container": "#fffbff",
        "surface-tint": "#0053db",
        "surface-container-highest": "#d8e3fb",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "stack-md": "16px",
        base: "4px",
        "stack-lg": "32px",
        "margin-mobile": "16px",
        gutter: "24px",
        "margin-desktop": "40px",
        "container-max": "1280px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        display: ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
