-- BriefFill Postgres schema (for Supabase)
-- Converted from SQLite schema. Run this in the Supabase SQL Editor.
-- Safe to re-run: drops existing tables first, then recreates.

-- Drop in reverse dependency order to avoid FK errors
DROP TABLE IF EXISTS portal_files CASCADE;
DROP TABLE IF EXISTS portal_responses CASCADE;
DROP TABLE IF EXISTS collaboration_portals CASCADE;
DROP TABLE IF EXISTS user_sessions CASCADE;
DROP TABLE IF EXISTS referral_credits CASCADE;
DROP TABLE IF EXISTS referrals CASCADE;
DROP TABLE IF EXISTS invoices CASCADE;
DROP TABLE IF EXISTS user_api_keys CASCADE;
DROP TABLE IF EXISTS webhook_deliveries CASCADE;
DROP TABLE IF EXISTS user_integrations CASCADE;
DROP TABLE IF EXISTS competitor_analyses CASCADE;
DROP TABLE IF EXISTS brief_outcomes CASCADE;
DROP TABLE IF EXISTS team_invites CASCADE;
DROP TABLE IF EXISTS brief_shares CASCADE;
DROP TABLE IF EXISTS team_members CASCADE;
DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS user_preferences CASCADE;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS field_definitions CASCADE;
DROP TABLE IF EXISTS briefs CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Extension for UUID generation (used by referral tokens, portal tokens, etc.)
-- create extension if not exists "pgcrypto";  -- already installed on Supabase by default

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  subscription_status TEXT DEFAULT 'free_trial',
  trial_end_date TIMESTAMPTZ,
  plan TEXT DEFAULT 'free',
  stripe_customer_id TEXT,
  stripe_subscription_id TEXT,
  brief_count_this_month INTEGER DEFAULT 0,
  brief_count_month TEXT,
  current_period_end TIMESTAMPTZ,
  cancel_at_period_end BOOLEAN DEFAULT false,
  locale TEXT DEFAULT 'en',
  referral_code TEXT,
  referred_by_user_id INTEGER,
  onboarding_email_sent_at TIMESTAMPTZ,
  reactivation_email_sent_at TIMESTAMPTZ,
  last_referral_activity_at TIMESTAMPTZ,
  avatar_url TEXT,
  first_name TEXT,
  last_name TEXT,
  display_name TEXT,
  bio TEXT,
  company TEXT,
  job_title TEXT,
  location TEXT,
  website TEXT,
  social_links JSONB,
  password_changed_at TIMESTAMPTZ,
  totp_secret TEXT,
  totp_enabled BOOLEAN DEFAULT false
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_referral_code ON users(referral_code);

CREATE TABLE IF NOT EXISTS briefs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  client_name TEXT NOT NULL,
  project_name TEXT NOT NULL,
  original_text TEXT NOT NULL,
  analyzed_text JSONB,
  completeness_score NUMERIC,
  missing_fields JSONB DEFAULT '[]',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'analyzed', 'email_sent')),
  industry TEXT,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_briefs_user_id ON briefs(user_id);

CREATE TABLE IF NOT EXISTS field_definitions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  field_name TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL,
  example_question TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  amount INTEGER NOT NULL,
  currency TEXT DEFAULT 'usd',
  plan TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'succeeded' CHECK (status IN ('succeeded', 'failed', 'refunded', 'bypass')),
  stripe_session_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_preferences (
  user_id BIGINT PRIMARY KEY,
  theme TEXT DEFAULT 'light',
  email_greeting TEXT DEFAULT 'Hi {clientName},',
  email_signoff TEXT DEFAULT 'Best regards,
{name}',
  email_template TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  notifications_email_enabled BOOLEAN DEFAULT true,
  notifications_brief_analysis BOOLEAN DEFAULT true,
  notifications_team_invites BOOLEAN DEFAULT true,
  notifications_portal_updates BOOLEAN DEFAULT true,
  notifications_referral_rewards BOOLEAN DEFAULT true,
  notifications_billing BOOLEAN DEFAULT true,
  notifications_product_updates BOOLEAN DEFAULT true,
  notifications_weekly_summary BOOLEAN DEFAULT true,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  owner_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  description TEXT,
  logo_url TEXT,
  FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS team_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  role TEXT NOT NULL DEFAULT 'viewer' CHECK (role IN ('admin', 'editor', 'viewer')),
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (team_id, user_id),
  FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS brief_shares (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brief_id BIGINT NOT NULL,
  team_id BIGINT NOT NULL,
  shared_by BIGINT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (brief_id, team_id),
  FOREIGN KEY (brief_id) REFERENCES briefs(id) ON DELETE CASCADE,
  FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE,
  FOREIGN KEY (shared_by) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS team_invites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_id BIGINT NOT NULL,
  email TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'viewer' CHECK (role IN ('admin', 'editor', 'viewer')),
  token TEXT NOT NULL UNIQUE,
  accepted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  FOREIGN KEY (team_id) REFERENCES teams(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS brief_outcomes (
  brief_id BIGINT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  status TEXT NOT NULL CHECK (status IN ('success', 'failure', 'in_progress')),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  FOREIGN KEY (brief_id) REFERENCES briefs(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS competitor_analyses (
  brief_id BIGINT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  competitors JSONB NOT NULL,
  common_strengths JSONB NOT NULL,
  common_gaps JSONB NOT NULL,
  opportunity TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  FOREIGN KEY (brief_id) REFERENCES briefs(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_integrations (
  user_id BIGINT NOT NULL,
  provider TEXT NOT NULL CHECK (provider IN ('notion', 'clickup', 'airtable', 'webhook')),
  api_key TEXT,
  target_id TEXT,
  target_id_2 TEXT,
  webhook_url TEXT,
  webhook_events JSONB,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (user_id, provider),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS webhook_deliveries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  event TEXT NOT NULL,
  url TEXT NOT NULL,
  status_code INTEGER,
  response_snippet TEXT,
  duration_ms INTEGER,
  error TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_api_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  key_hash TEXT NOT NULL UNIQUE,
  last_used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  is_active BOOLEAN DEFAULT true,
  key_prefix TEXT,
  revoked_at TIMESTAMPTZ,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS invoices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  stripe_invoice_id TEXT UNIQUE,
  amount INTEGER,
  currency TEXT DEFAULT 'usd',
  status TEXT,
  invoice_pdf TEXT,
  period_start TIMESTAMPTZ,
  period_end TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS referrals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  referrer_user_id BIGINT NOT NULL,
  referred_user_id BIGINT NOT NULL UNIQUE,
  referral_code TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending_signup' CHECK (status IN ('pending_signup', 'signed_up', 'paid', 'rewarded', 'cancelled', 'rejected')),
  referrer_credit_cents INTEGER DEFAULT 1000,
  friend_reward TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  qualified_at TIMESTAMPTZ,
  rewarded_at TIMESTAMPTZ,
  cancelled_at TIMESTAMPTZ,
  rejected_reason TEXT,
  ip_address TEXT,
  FOREIGN KEY (referrer_user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (referred_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_referrals_referrer ON referrals(referrer_user_id);
CREATE INDEX IF NOT EXISTS idx_referrals_code ON referrals(referral_code);

CREATE TABLE IF NOT EXISTS referral_credits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  amount_cents INTEGER NOT NULL,
  reason TEXT NOT NULL,
  referral_id BIGINT,
  applied_to_invoice_id BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (referral_id) REFERENCES referrals(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_referral_credits_user ON referral_credits(user_id);

CREATE TABLE IF NOT EXISTS user_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  token_hash TEXT NOT NULL,
  user_agent TEXT,
  ip_address TEXT,
  last_active_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS collaboration_portals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brief_id BIGINT NOT NULL REFERENCES briefs(id) ON DELETE CASCADE,
  token TEXT UNIQUE NOT NULL,
  view_count INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  last_activity TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS portal_responses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  portal_id BIGINT NOT NULL REFERENCES collaboration_portals(id) ON DELETE CASCADE,
  field_name TEXT NOT NULL,
  response TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS portal_files (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  portal_id BIGINT NOT NULL REFERENCES collaboration_portals(id) ON DELETE CASCADE,
  field_name TEXT,
  file_name TEXT NOT NULL,
  stored_name TEXT NOT NULL,
  file_size INTEGER,
  mime_type TEXT,
  uploaded_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed field_definitions
INSERT INTO field_definitions (field_name, description, example_question) VALUES
  ('Project Overview', 'What is the project about? What is the goal?', 'Could you briefly describe the project and its primary goal? How will success be measured?'),
  ('Target Audience', 'Who is this for? Demographics, psychographics, current behavior.', 'Who is the primary audience for this project? Can you describe their age, profession, and what they care about most?'),
  ('Core Problem', 'What problem does this product/service solve for the audience?', 'What specific problem does your product/service solve that existing solutions don''t address?'),
  ('Solution/Offer', 'What is the actual offering? Features, benefits, unique value proposition.', 'What is the core offering? What makes it different from competitors?'),
  ('Key Benefits', 'What are the top 3-5 benefits the audience will experience?', 'What are the main benefits someone will get from using this? Why should they care?'),
  ('Tone of Voice', 'What is the brand personality? Professional? Playful? Authoritative?', 'What tone should the messaging use? Is the brand more professional, friendly, bold, or humorous?'),
  ('Brand Guidelines', 'Colors, fonts, logo usage, design system links.', 'Do you have existing brand guidelines or a style guide I should follow? If not, any preferences on colors/fonts?'),
  ('Deliverables', 'What exactly are you delivering? List of all outputs.', 'Can you provide a list of all deliverables expected from this project? Please be as specific as possible.'),
  ('Timeline', 'When is this needed? Milestones, final deadline.', 'What is the ideal timeline for this project? Are there any specific milestones or important dates?'),
  ('Budget', 'What is the approximate budget? Helps scope the work.', 'Do you have a budget range in mind for this project? This helps me suggest the best scope of work.'),
  ('Competitors', 'Who else is doing something similar?', 'Who are your main competitors? What do you think they do well/poorly?'),
  ('Call to Action', 'What do you want the audience to do after consuming this?', 'What is the primary action you want the audience to take after seeing this (e.g., sign up, buy, contact)?')
ON CONFLICT (field_name) DO NOTHING;
